name: Check push

on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Build project
    uses: WrenSecurity/.github/.github/workflows/build-project.yml
  sonar:
    needs: build
    name: Sonar analysis
    if: github.ref_name == 'main'
    uses: WrenSecurity/.github/.github/workflows/sonar-maven.yml
    with:
      java-version: "17" #TODO: jaka bude testovaci verze
      project-key: "" #TODO: var nebo hardcoded
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
